spring.application.name=Salesforce MCP Server

# MCP Server Config
spring.ai.mcp.server.type=ASYNC
spring.ai.mcp.server.name=salesforce-mcp-server
spring.ai.mcp.server.version=1.0.0

# Web Config
spring.main.web-application-type=reactive
spring.main.banner-mode=off

# Server Port
server.port=8080

# Logging
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n
logging.file.name=./logs/salesforce-mcp-server.log
logging.level.root=INFO
logging.level.com.idfcfirstbank=DEBUG